
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
leaderElection:
  leaderElect: false
  leaseDuration: 15s
  renewDeadline: 10s
  resourceName: matrix-scheduler
  resourceNamespace: kube-system
  retryPeriod: 2s
profiles:
  - schedulerName: matrix-scheduler
    plugins:
      filter:
        enabled:
        - name: MigScheduling
        disabled:
        - name: "*"